# Generated by Django 5.2 on 2025-05-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
