# Generated by Django 5.2 on 2025-05-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_images_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
