# Generated by Django 5.2 on 2025-05-08 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
