# Generated by Django 5.2 on 2025-05-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
