# Generated by Django 5.2 on 2025-05-08 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
