# Generated by Django 5.2 on 2025-05-09 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
