# Generated by Django 5.2 on 2025-05-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
