# Generated by Django 5.2 on 2025-05-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_alter_images_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='dislikes',
            field=models.IntegerField(null=True),
        ),
    ]
