# Generated by Django 5.2 on 2025-06-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0021_alter_comments_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
