# Generated by Django 5.2 on 2025-06-08 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0028_alter_images_name_alter_person_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
