# Generated by Django 5.2 on 2025-06-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0030_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
